version: "2"
services:
  campaigns_ms:
    build: .
    command: npm start
    ports:
      - "3302:4005"
    links:
      - campaigns_db
    depends_on:
      - campaigns_db
  campaigns_db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "4302:27017"
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "4305:4305"
